/* eslint-disable @typescript-eslint/ban-ts-comment */
 
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  accordion: {
    name: 'accordion',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/accordion.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/accordion.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'alert-dialog': {
    name: 'alert-dialog',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['@fab-ui/button'],
    files: [
      {
        path: 'registry/default/ui/alert-dialog.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/alert-dialog.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  autocomplete: {
    name: 'autocomplete',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['@fab-ui/input'],
    files: [
      {
        path: 'registry/default/ui/autocomplete.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/autocomplete.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  avatar: {
    name: 'avatar',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/avatar.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/avatar.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  badge: {
    name: 'badge',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/badge.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/badge.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  button: {
    name: 'button',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/button.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/button.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  card: {
    name: 'card',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/card.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/card.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  checkbox: {
    name: 'checkbox',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/checkbox.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/checkbox.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-group': {
    name: 'checkbox-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/checkbox-group.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/checkbox-group.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  collapsible: {
    name: 'collapsible',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/collapsible.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/collapsible.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  combobox: {
    name: 'combobox',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['@fab-ui/button', '@fab-ui/input-group'],
    files: [
      {
        path: 'registry/default/ui/combobox.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/combobox.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'context-menu': {
    name: 'context-menu',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/context-menu.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/context-menu.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  dialog: {
    name: 'dialog',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/dialog.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/dialog.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dropdown-menu': {
    name: 'dropdown-menu',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/dropdown-menu.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/dropdown-menu.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  field: {
    name: 'field',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/field.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/field.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  fieldset: {
    name: 'fieldset',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/fieldset.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/fieldset.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  form: {
    name: 'form',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/form.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/form.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  input: {
    name: 'input',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/input.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/input.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'input-group': {
    name: 'input-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: [
      '@fab-ui/button',
      '@fab-ui/input',
      '@fab-ui/textarea',
    ],
    files: [
      {
        path: 'registry/default/ui/input-group.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/input-group.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  label: {
    name: 'label',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/label.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/label.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  meter: {
    name: 'meter',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/meter.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/meter.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'number-field': {
    name: 'number-field',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/number-field.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/number-field.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  popover: {
    name: 'popover',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/popover.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/popover.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'preview-card': {
    name: 'preview-card',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/preview-card.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/preview-card.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  progress: {
    name: 'progress',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/progress.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/progress.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  radio: {
    name: 'radio',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/radio.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/radio.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'scroll-area': {
    name: 'scroll-area',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/scroll-area.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/scroll-area.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  select: {
    name: 'select',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/select.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/select.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  separator: {
    name: 'separator',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/separator.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/separator.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  slider: {
    name: 'slider',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/slider.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/slider.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  switch: {
    name: 'switch',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/switch.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/switch.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  tabs: {
    name: 'tabs',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/tabs.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/tabs.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  textarea: {
    name: 'textarea',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/textarea.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/textarea.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'toggle-group': {
    name: 'toggle-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['@fab-ui/toggle'],
    files: [
      {
        path: 'registry/default/ui/toggle-group.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/toggle-group.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  toggle: {
    name: 'toggle',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/toggle.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/toggle.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  toolbar: {
    name: 'toolbar',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/toolbar.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/toolbar.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  tooltip: {
    name: 'tooltip',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/ui/tooltip.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/ui/tooltip.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'accordion-default': {
    name: 'accordion-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['accordion'],
    files: [
      {
        path: 'registry/default/examples/accordion-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/accordion-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'alert-dialog-default': {
    name: 'alert-dialog-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['alert-dialog'],
    files: [
      {
        path: 'registry/default/examples/alert-dialog-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/alert-dialog-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'autocomplete-default': {
    name: 'autocomplete-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['autocomplete'],
    files: [
      {
        path: 'registry/default/examples/autocomplete-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/autocomplete-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'avatar-default': {
    name: 'avatar-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['avatar'],
    files: [
      {
        path: 'registry/default/examples/avatar-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/avatar-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'badge-default': {
    name: 'badge-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: [
      {
        path: 'registry/default/examples/badge-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/badge-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-default': {
    name: 'button-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/button-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-outline': {
    name: 'button-outline',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-outline.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/button-outline.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-secondary': {
    name: 'button-secondary',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-secondary.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/button-secondary.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-ghost': {
    name: 'button-ghost',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-ghost.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/button-ghost.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-link': {
    name: 'button-link',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-link.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/button-link.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-icon': {
    name: 'button-icon',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-icon.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/button-icon.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'button-with-icon': {
    name: 'button-with-icon',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'registry/default/examples/button-with-icon.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/button-with-icon.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'card-default': {
    name: 'card-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['card'],
    files: [
      {
        path: 'registry/default/examples/card-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/card-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-default': {
    name: 'checkbox-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox'],
    files: [
      {
        path: 'registry/default/examples/checkbox-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-checked': {
    name: 'checkbox-checked',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox'],
    files: [
      {
        path: 'registry/default/examples/checkbox-checked.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-checked.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-disabled': {
    name: 'checkbox-disabled',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox'],
    files: [
      {
        path: 'registry/default/examples/checkbox-disabled.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-disabled.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-with-label': {
    name: 'checkbox-with-label',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox', 'label'],
    files: [
      {
        path: 'registry/default/examples/checkbox-with-label.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-with-label.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-group-default': {
    name: 'checkbox-group-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox', 'checkbox-group', 'label'],
    files: [
      {
        path: 'registry/default/examples/checkbox-group-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-group-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox-group-with-field': {
    name: 'checkbox-group-with-field',
    description: '',
    type: 'registry:example',
    registryDependencies: ['checkbox', 'checkbox-group', 'field', 'label'],
    files: [
      {
        path: 'registry/default/examples/checkbox-group-with-field.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/checkbox-group-with-field.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'collapsible-default': {
    name: 'collapsible-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['collapsible'],
    files: [
      {
        path: 'registry/default/examples/collapsible-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/collapsible-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'combobox-default': {
    name: 'combobox-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['combobox'],
    files: [
      {
        path: 'registry/default/examples/combobox-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/combobox-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'combobox-with-clear': {
    name: 'combobox-with-clear',
    description: '',
    type: 'registry:example',
    registryDependencies: ['combobox'],
    files: [
      {
        path: 'registry/default/examples/combobox-with-clear.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/combobox-with-clear.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'context-menu-default': {
    name: 'context-menu-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['context-menu'],
    files: [
      {
        path: 'registry/default/examples/context-menu-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/context-menu-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'context-menu-with-submenu': {
    name: 'context-menu-with-submenu',
    description: '',
    type: 'registry:example',
    registryDependencies: ['context-menu'],
    files: [
      {
        path: 'registry/default/examples/context-menu-with-submenu.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/context-menu-with-submenu.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dialog-default': {
    name: 'dialog-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['dialog', 'button'],
    files: [
      {
        path: 'registry/default/examples/dialog-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/dialog-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dialog-no-close-button': {
    name: 'dialog-no-close-button',
    description: '',
    type: 'registry:example',
    registryDependencies: ['dialog', 'button'],
    files: [
      {
        path: 'registry/default/examples/dialog-no-close-button.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/dialog-no-close-button.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dropdown-menu-default': {
    name: 'dropdown-menu-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['dropdown-menu', 'button'],
    files: [
      {
        path: 'registry/default/examples/dropdown-menu-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/dropdown-menu-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dropdown-menu-with-submenu': {
    name: 'dropdown-menu-with-submenu',
    description: '',
    type: 'registry:example',
    registryDependencies: ['dropdown-menu', 'button'],
    files: [
      {
        path: 'registry/default/examples/dropdown-menu-with-submenu.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/dropdown-menu-with-submenu.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'field-default': {
    name: 'field-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['field', 'input'],
    files: [
      {
        path: 'registry/default/examples/field-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/field-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'field-with-description': {
    name: 'field-with-description',
    description: '',
    type: 'registry:example',
    registryDependencies: ['field', 'input'],
    files: [
      {
        path: 'registry/default/examples/field-with-description.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/field-with-description.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'fieldset-default': {
    name: 'fieldset-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['fieldset', 'field', 'input'],
    files: [
      {
        path: 'registry/default/examples/fieldset-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/fieldset-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'form-default': {
    name: 'form-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['form', 'field', 'input', 'button'],
    files: [
      {
        path: 'registry/default/examples/form-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/form-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'input-default': {
    name: 'input-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: [
      {
        path: 'registry/default/examples/input-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/input-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'input-disabled': {
    name: 'input-disabled',
    description: '',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: [
      {
        path: 'registry/default/examples/input-disabled.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/input-disabled.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'input-group-default': {
    name: 'input-group-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['input-group', 'dropdown-menu', 'separator'],
    files: [
      {
        path: 'registry/default/examples/input-group-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/input-group-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'label-default': {
    name: 'label-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['label', 'input'],
    files: [
      {
        path: 'registry/default/examples/label-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/label-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'meter-default': {
    name: 'meter-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['meter'],
    files: [
      {
        path: 'registry/default/examples/meter-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/examples/meter-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'meter-with-label': {
    name: 'meter-with-label',
    description: '',
    type: 'registry:example',
    registryDependencies: ['meter'],
    files: [
      {
        path: 'registry/default/examples/meter-with-label.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/meter-with-label.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'number-field-default': {
    name: 'number-field-default',
    description: '',
    type: 'registry:example',
    registryDependencies: ['number-field'],
    files: [
      {
        path: 'registry/default/examples/number-field-default.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/number-field-default.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'number-field-with-scrub': {
    name: 'number-field-with-scrub',
    description: '',
    type: 'registry:example',
    registryDependencies: ['number-field'],
    files: [
      {
        path: 'registry/default/examples/number-field-with-scrub.tsx',
        type: 'registry:example',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import('@/registry/default/examples/number-field-with-scrub.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  utils: {
    name: 'utils',
    description: '',
    type: 'registry:lib',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/default/lib/utils.ts',
        type: 'registry:lib',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/default/lib/utils.ts');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
